version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CyberLab
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:NM71zguegpHW2OrvfN8jjIWLDbSCkF14VlZpp3nZV4w=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=labs_virtualization
      - DB_USERNAME=root
      - DB_PASSWORD=DB_PASSWORD=
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=e4aef5e7ca697d
      - MAIL_PASSWORD=cc62f1bcbe9300
      - MAIL_ENCRYPTION=tls
    depends_on:
      - mysql
    networks:
      - cyberlab_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labs_virtualization
      MYSQL_USER=root: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cyberlab_network

networks:
  cyberlab_network:
    driver: bridge

volumes:
  mysql_data: